### ISSUE TITLE
Internet disconnected

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/ccra-book#34]
I just realized, we need to check if internet is disconnected. If it is, we need to display a message telling the user an internet connection is required.
This can probably be done via a cordova plugin?

**Comment by torch2424** [comment]
As of right now, if their internet is disconnected, and they attempt to get a page, I trust they will get an error saying check their internet connection and try again later

**Comment by julianpoy** [comment]
Alright, would you check to make sure that's the case and then close this?

**Comment by torch2424** [comment]
sure

**Comment by torch2424** [comment]
So, we get error zero back for disconnected, and I do catch it, but I dont say to check your internet, connection, I think I added it in some error blocks but not others. Here is a screen:

![screenshot-192 168 100 101 8100 2016-01-24 16-48-54](https://cloud.githubusercontent.com/assets/1448289/12540248/84200132-c2ba-11e5-891c-7d01de64996d.png)


So how about I just check for error zero, which usually means they are not connected, or their firewall is acting up, and just inform them that they app needs internet whenever we get error zero.

I would like to close this issue along with #31 since It is when I wanted to implement and error handler service

**Comment by julianpoy** [comment]
Just say "It seems your internet connection isn't working right now. Please try again when you have internet."

**Comment by torch2424** [comment]
Cool, sounds good

**Comment by julianpoy** [comment]
Alright, do it in that branch then :dancer:
